version: '3.9'
services:
  tgbot:
    build: .
    container_name: telegram_bot
    restart: always
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: islam20011
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: islam20011
    restart: always
    volumes:
      - redis_data:/data redis
    ports:
      - "6379:6379"
  filed:
    command: /file.d/file.d --config /config.yaml
    image: ozonru/file.d:latest
    volumes:
      - ./data/log.txt:/tmp/logs/log.txt
      - ./data/offsets.yaml:/tmp/offsets.yaml
      - ./filed.yml:/config.yaml
    links:
      - graylog
    depends_on:
      - graylog
  mongodb:
    image: mongo:3
    volumes:
      - ./data/mongo:/data/db
  elasticsearch:
    image: elasticsearch:7.17.6
    # volumes:
    #   - ./data/elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  graylog:
    image: graylog/graylog:4.3
    volumes:
      - ./graylog.conf:/usr/share/graylog/data/config/graylog.conf
    environment:
      # (must be at least 16 characters)
      - GRAYLOG_PASSWORD_SECRET=EabOdthinPafivup
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:7555
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:7555/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 7555:7555
      # Syslog TCP
      - 8514:8514
      # Syslog UDP
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
    extra_hosts:
      - host.docker.internal:host-gateway
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./data:/var/lib/grafana
    links:
      - prometheus

volumes:
  postgres_data:
  redis_data: